laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index');

Route::get('auth/login', function () {
    $credentilas = [
        'email' => 'gldawo@icloud.com',
        'password' => '1234',
    ];

    if (!auth()->attempt($credentilas, false)) {
        return 'Login Fail';
    }

    return redirect('protected');
//    return 'Success';
});

Route::get('/protected', function () {
    dump(session()->all());
    if (!auth()->check()) {
        return 'Who are you?';
    }

    return 'Welcome ' . auth()->user()->name;
});

Route::get('/auth/logout', function () {
    auth()->logout();

    return 'See you later';
});

Route::resource('articles', 'ArticleController');

// Auto generation Auth Route
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// DB::listen(function ($query) {
//     var_dump($query->sql);
// });

Route::get('mail', function () {
    $article = \App\Article::with('user')->find(1);

    return Mail::send(
        'emails.articles.created',
        compact('article'),
        function ($message) use ($article) {
            $message->to('gldawo@icloud.com');
            $message->subject('새 글이 등록되었습니다 -' . $article->title);
        }
    );
});

Route::get('docs/{file?}', 'DocsController@show');

Route::get('docs/images/{image}', 'DocsController@image')
    ->where('image', '[\pL-\pN\._-]+-img-[0-9]{2}.png');

laravel/app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Article
 *
 * @property int $id
 * @property int $user_id
 * @property string $title
 * @property string $content
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Tag[] $tags
 * @property-read \App\User $user
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Article whereContent($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Article whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Article whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Article whereTitle($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Article whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Article whereUserId($value)
 * @mixin \Eloquent
 */
class Article extends Model
{
    protected $fillable = ['title', 'content'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }
}

laravel/app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Article;
use App\Http\Requests\ArticleRequest;
use Illuminate\Http\Request;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
//        $articles = \App\Article::get();
//        $articles->load('user');
//        $articles = \App\Article::with('user')->get();
        $articles = Article::latest()->paginate(3);

        return view('articles.index', compact('articles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('articles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ArticleRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(ArticleRequest $request)
    {
        /** @var Article $article */
        $article = \App\User::find(1)->articles()->create($request->all());


        if (!$article) {
            return back()->with('flash_message', '글이 저장되지 않았습니다')->withInput();
        }

        var_dump('event throw');
        event(new \App\Events\ArticlesEvent($article));
        var_dump('event thrown');

        // return redirect(route('articles.index'))->with('flash_message', '작성하신 글이 저장되었습니다');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return array
     */
    public function show($id)
    {
        $article = Article::findOrFail($id);
        // dd($article);

        return $article->toArray();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return __METHOD__;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        return __METHOD__;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        return __METHOD__;
    }
}

laravel/resources/views/articles/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>새 포럼 글쓰기</h1>

        <hr>

        <form action="{{ route('articles.store') }}" method="POST">
            {!! csrf_field() !!}

            <div class="form-group" {{ $errors->has('title') ? 'has-error' : '' }}>
                <label for="title">제목</label>
                <input type="text" name="title" id="title" value="{{ old('title') }}" class="form-control">
                {!! $errors->first('title', '<span class="form-error">:message</span>') !!}
            </div>

            <div class="form-group" {{ $errors->has('content') ? 'has-error' : '' }}>
                <label for="title">본문</label>
                <textarea name="content" id="content" rows="10" class="form-control">{{ old('content') }}</textarea>
                {!! $errors->first('content', '<span class="form-error">:message</span>') !!}
            </div>

            <div class="form-control">
                <button type="submit" class="btn btn-primary">저장하기</button>
            </div>
        </form>
    </div>
@stop

laravel/resources/views/articles/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>글 목록</h1>
        <hr/>
        <ul>
            @forelse($articles as $article)
                <li>
                    {{ $article->title }}
                    <small>
                        by {{ $article->user->name }}
                    </small>
                </li>
            @empty
                <p>글이 없습니다.</p>
            @endforelse
        </ul>
        @if($articles->count())
            <div class="text-center">
                {!! $articles->render() !!}
            </div>
        @endif
    </div>
@stop